### ISSUE TITLE
suggested changes before initial release

### ISSUE THREAD

**Issue by kt** [getsenic/nuimo-linux-python#1]
- ~~remove fly_event TODO~~
- ~~rename nuimocore.py to nuimo.py~~
- rename NuimoController to Nuimo?
- ~~rename examples/nuimo.py?~~ Renamed to examples/test.py
- default for brightness set in NuimoController constructor is ignored
- default for display_interval set in NuimoController constructor is ignored
- write_matrix has timeout as compulsory parameter, should use constructor default

**Comment by larsblumberg** [comment]
I'm closing this issue in favor of [the new Nuimo SDK that will be based on BlueZ's D-Bus API](https://github.com/getsenic/nuimo-linux-python/pull/20)
