### ISSUE TITLE
Error in python3: double free or corruption (fasttop)

### ISSUE THREAD

**Issue by naimo84** [getsenic/nuimo-linux-python#12]
Most of the time, it takes 2 or 3 tries, to get the script running. The first error occurs very often. 

Python 3.5.0 (default, Sep 14 2016, 20:23:07)

```
naimo:~ $ sudo python3 /opt/nuimo/examples/test.py
*** Error in `python3': double free or corruption (fasttop): 0x75b016e8 ***

naimo:~ $ sudo python3 /opt/nuimo/examples/test.py
Traceback (most recent call last):
  File "/opt/nuimo/examples/test.py", line 55, in <module>
    main()
  File "/opt/nuimo/examples/test.py", line 27, in main
    nuimo.connect()
  File "/opt/nuimo/examples/nuimo.py", line 194, in connect
    GATTRequester.connect(self, wait=True, channel_type="random")
RuntimeError: Could not update HCI connection: Connection timed out

naimo:~ $ sudo python3 /opt/nuimo/examples/test.py
Displaying LED Matrix...
Waiting for Nuimo events, use CTRL+C to quit
```

I don't know, if it's related to this problem, but gatttool also has a problem 

`Connection successful
[FA:B7:DD:4A:BE:1B][LE]> characteristics
Error: Discover all characteristics failed: Internal application error: I/O
[FA:B7:DD:4A:BE:1B][LE]>
(gatttool:28989): GLib-CRITICAL **: g_queue_pop_head: assertion 'queue != NULL' failed`

or another one

`[FA:B7:DD:4A:BE:1B][LE]> connect
Attempting to connect to FA:B7:DD:4A:BE:1B
Error: connect error: Connection timed out (110)`

**Comment by larsblumberg** [comment]
Unfortunately we can't reproduce this behavior. Given that your `gatttool` also fails I would assume that the error source might be the same.

**Comment by fliiiix** [comment]
```
pi@raspberrypi:~/nuimo-linux-python $ sudo PYTHONPATH=. python examples/test.py
INFO:nuimo:hci0, started Nuimo discovery
started discovery
INFO:nuimo:hci0, discovered Bluetooth device D8:3F:75:D5:45:0E, {'appearance': 384, 'flags': 6, 'name': 'Nuimo', 'uuids': [6159, 6154]}
INFO:nuimo:hci0, NuimoController(D8:3F:75:D5:45:0E)
added Nuimo: NuimoController(D8:3F:75:D5:45:0E)
finished discovery
INFO:nuimo:D8:3F:75:D5:45:0E: connecting
*** Error in `python': double free or corruption (fasttop): 0x759016a8 ***
pi@raspberrypi:~/nuimo-linux-python $ python --version
Python 2.7.9
```

I saw similar errors and the problem that it often failed to connect. A workaround which worked well for me is to remove the `nuimo.pyc` file before each run (doesn't work always).

**Comment by jo-me** [comment]
I have the same issue on RPI3 with python2
Sometimes, directly after starting it (probably when the connection is attempted)

`*** Error in `python': double free or corruption (fasttop): 0x75901710 ***`

Removing the pyc-file did not help it..

I also saw this once (same as mentioned above):
`RuntimeError: Could not update HCI connection: Connection timed out`

**Comment by larsblumberg** [comment]
I'm closing this issue in favor of [the new Nuimo SDK that will be based on BlueZ's D-Bus API](https://github.com/getsenic/nuimo-linux-python/pull/20)
