### ISSUE TITLE
Raspberry Pi 1 fails due to discover_characteristics

### ISSUE THREAD

**Issue by jo-me** [getsenic/nuimo-linux-python#16]
Hi,

did you ever get it running on a raspberry pi 1?
The discover_characteristics part hangs here. 

Interestingly enough, the raspberry pi demo script you provided here https://github.com/getsenic/nuimo-raspberrypi-demo worked fine on the same device..

Jochen

**Comment by larsblumberg** [comment]
Hi Jochen,

the Raspberry PI demo uses a different BLE library (bluepy) than this SDK (pygattlib). It seems to be difficult to find a library that properly supports all Linux distributions. We're however working to make this SDK work with Pi 1, too.

Best
Lars

**Comment by jo-me** [comment]
Hi Lars, 
I see..   I wanted to get the Nuimo up and running using my old PI while the newer one is running 24/7 as music player.  So the Pi2 is my target platform anyway. 

Just to let you know, the NuimoJS library works on the Raspberry 1 Model B (512MB RAM) and (according to the project page) also on the rpi 3. 
See here: https://github.com/nathankunicki/nuimojs

regards,
Jochen

**Comment by larsblumberg** [comment]
Hi @jo-me, please try our all new Nuimo Python SDK. It now uses BlueZ's D-Bus API directly. Please find all information here: https://github.com/getsenic/nuimo-linux-python
