### ISSUE TITLE
nuimoctl broken after update to 0.24

### ISSUE THREAD

**Issue by jo-me** [getsenic/nuimo-linux-python#26]
Hi Lars,
just upgraded to 0.24 via pip3....-U. 
Now, nuimoctl throws an error:

volumio@volumio:~$ sudo nuimoctl --discover
Traceback (most recent call last):
  File "/usr/local/bin/nuimoctl", line 9, in <module>
    load_entry_point('nuimo==0.2.4', 'console_scripts', 'nuimoctl')()
  File "/usr/local/lib/python3.4/dist-packages/nuimoctl.py", line 108, in main
    controller_manager = nuimo.ControllerManager(adapter_name=args.adapter)
  File "/usr/local/lib/python3.4/dist-packages/nuimo/nuimo.py", line 18, in __init__
    super().__init__(adapter_name)
TypeError: object.__init__() takes no parameters

I've restarted the bluetooth daemon but did not change the outcome.
Do I have to restart the whole system?

Jochen

**Comment by larsblumberg** [comment]
Sorry for that. Will release a fix tomorrow.

For now you can do the following: Open the file "/usr/local/lib/python3.4/dist-packages/gatt/gatt.py" and replace in the line `if platform.system() == 'Darwin':` the word `Darwin` with `Linux`.

**Comment by larsblumberg** [comment]
Please update the `gatt` module, version 0.1.6 will fix it.
