### ISSUE TITLE
connect failed: No such property 'ServicesResolved'

### ISSUE THREAD

**Issue by miloit** [getsenic/nuimo-linux-python#30]
Hello yhis is my error:

Nuimo controller C7:BC:F2:F9:48:79 connecting...
Nuimo controller C7:BC:F2:F9:48:79 connect failed: No such property 'ServicesResolved'

**Comment by larsblumberg** [comment]
Which version of BlueZ are you using? You can find out by typing `bluetoothctl --version`. Make sure it's at least version 5.43, better [install the most recent version](https://github.com/getsenic/nuimo-linux-python#updatinginstalling-bluez-via-apt-get).

**Comment by miloit** [comment]
5.44 as described in your readme

**Comment by larsblumberg** [comment]
That's strange – we never encountered such error. Which Linux distro are you using? Which board and which Bluetooth adapter are you using?

**Comment by miloit** [comment]
It is solved. I rebuild bluez and everything is fine now
